currencies:
  tickers:
    USD Index: usd_i
    EUR/USD: eurusd
    GBP/USD: gbpusd
    USD/JPY: usdjpy
    USD/CAD: usdcad
    USD/SEK: usdsek
    USD/CHF: usdchf

  dxy_base_constant: 50.14348112

  dxy_weights:
    EUR/USD: -0.576
    USD/JPY: 0.136
    GBP/USD: -0.119
    USD/CAD: 0.091
    USD/SEK: 0.042
    USD/CHF: 0.036
  
  fetch_name: "currencies"

key_sectors:
  tickers:
        Technology: "xlk.us"
        Energy: "xle.us"
        Consumer Staples: "xlp.us"
        Consumer Discretionary: "xly.us"
        Healthcare: "xlv.us"
        Industrials: "xli.us"
        Materials: "xlb.us"
  fetch_name: "key sectors"

financial:
  tickers:
    US Financials ETF: xlf.us
    European Banks ETF: eufn.us
    Global Financials ETF: ixg.us
    Asia-Pacific ETF: aia.us
    China Financials ETF: fxi.us
    Japan Banks ETF: ewj.us
    Latin America Financials ETF: ilf.us
    Canada Banks ETF: ewc.us
    Australia Banks ETF: ewa.us
  fetch_name: "financial"

stocks:
  tickers:
    S&P500: "^spx"
    NASDAQ: "^ndq"
    Dow Jones: "^dji"
    FTSE250: "^ftm"
    DAX: "^dax"
    Nikkei225: "^nkx"
    Shanghai: "^shc"
    Russell2000: "iwm.us"
    MSCI Emerging Markets: "eem.us"
    MSCI World: "urth.us"
    All Country World: "acwi.us"
    Euro Stoxx 50: "fez.us"
  fetch_name: "stocks"

commodities:
  tickers:
    United States Oil Fund: "uso.us"
    United States 12 Month Oil Fund: "usl.us"
    VanEck Gold Miners: "gdx.us"
    SPDR Gold Shares: "gld.us"
    iShares MSCI Global Gold Miners ETF: "ring.us"
    Global X Silver Miners ETF: "sil.us"
    iShares Silver Trust: "slv.us"
    Global X Copper Miners: "copx.us"
    First Trust Natural Gas ETF: "fcg.us"
    Corn ETF: "corx.us"
    Wheat ETF: "whtx.us"
    Agriculture ETF: "dba.us"
    iShares MSCI Global Metals & Mining Producers ETF: "pick.us"
    VanEck Rare Earth and Strategic Metals ETF: "remx.us"
  fetch_name: "comodities"

bonds_interest:
  sources:
    - type: "stooq"
      base_url: "https://stooq.com/q/d/l/"
      tickers:
        iShares 20+ Year Treasury Bond ETF: "tlt.us"
        iShares 7-10 Year Treasury Bond ETF: "ief.us"
        iShares 1-3 Year Treasury Bond ETF: "shy.us"
        Vanguard Total Bond Market ETF: "bnd.us"
        iShares Core U.S. Aggregate Bond ETF: "agg.us"
        iShares TIPS Bond ETF: "tip.us"
        iShares iBoxx $ Investment Grade Corporate Bond ETF: "lqd.us"
        iShares iBoxx $ High Yield Corporate Bond ETF: "hyg.us"
        SPDR Bloomberg High Yield Bond ETF: "jnk.us"
        SPDR Bloomberg 1-3 Month T-Bill ETF: "bil.us"
        Global X Interest Rate Hedge ETF: "rate.us"
    - type: "fred"
      base_url: "fred"  
      tickers:
        "10_Year_Treasury": "DGS10"
        "3_Month_Treasury": "DTB3"
        "Federal_Funds_Rate": "FEDFUNDS"
  fetch_name: "bonds_interest"

cryptos:
  tickers:
    BTC: "btc.v"
    ETH: "eth.v"
    XRP: "xrp.v"
    BNB: "bnb.v"
    SOL: "sol.v"
  fetch_name: "cryptos"

base_url: "https://stooq.com/q/d/l/"
